#!/usr/bin/env python3

##################################################################################
# Copyright (c) 2020, Kenneth P. J. Dyer <kenneth@avoceteditors.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of the copyright holder nor the name of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
##################################################################################

# Module Imports
import argparse
import sys

# Local Imports
import libdyer
import libdyer.meetup
import libdyer.log

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
            prog='mup')

    parser.set_defaults(func=libdyer.report_version)

    # Options
    opts = parser.add_argument_group("Options")

    opts.add_argument("-d", "--debug", action="store_true",
            help="Enables debugging messages in log output")
    opts.add_argument("-v", "--verbose", action="store_true",
            help="Enables verbose logging messages")

    # Commands
    cmds = parser.add_subparsers(title="Commands")

    list_info = cmds.add_parser("list", help="Lists information on current groups")
    list_info.set_defaults(func=libdyer.meetup.list_inactive)

    list_cmds = list_info.add_subparsers(title="List Commands")

    list_inactive = list_cmds.add_parser("inactive", help="Lists inactive members")
    list_inactive.set_defaults(func=libdyer.meetup.list_inactive)


    # Parse Arguments
    args = parser.parse_args()


    setattr(args, "script_name", "mup")
    setattr(args, "script_byline", "Meetup Client for LibDyer")

    # Init Logger
    libdyer.log.set_logger(args.verbose, args.debug)

    args.func(args)

    sys.exit(0)



